export default {
  psql: [
    'bigint',
    'int8',
    'bigserial',
    'serial8',
    'bit',
    'bit varying',
    'varbit',
    'boolean',
    'bool',
    'box',
    'bytea',
    'character',
    'char',
    'character varying',
    'cidr',
    'circle',
    'date',
    'double precision',
    'float8',
    'inet',
    'integer',
    'int',
    'int4',
    'interval',
    'json',
    'jsonb',
    'line',
    'lseg',
    'macaddr',
    'money',
    'numeric',
    'decimal',
    'path',
    'pg_lsn',
    'point',
    'polygon',
    'real',
    'float4',
    'smallint',
    'int2',
    'smallserial',
    'serial2',
    'serial',
    'serial4',
    'text',
    'time',
    'timetz',
    'timestamp',
    'timestamptz',
    'tsquery',
    'tsvector',
    'txid_snapshot',
    'uuid',
    'xml'
  ],
  sqlite: [
    'INT',
    'INTEGER',
    'TINYINT',
    'SMALLINT',
    'MEDIUMINT',
    'BIGINT',
    'UNSIGNED BIG INT',
    'INT2',
    'INT8',
    'CHARACTER(20)',
    'VARCHAR(255)',
    'VARYING CHARACTER(255)',
    'NCHAR(55)',
    'NATIVE CHARACTER(70)',
    'NVARCHAR(100)',
    'TEXT',
    'CLOB',
    'BLOB',
    'no datatype specified',
    'REAL',
    'DOUBLE',
    'DOUBLE PRECISION',
    'FLOAT',
    'NUMERIC',
    'DECIMAL(10,5)',
    'BOOLEAN',
    'DATE',
    'DATETIME'
  ]
};
